apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: skuleshov/micro_frontend:v0.0.1
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_health"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "127.0.0.1:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "127.0.0.1:7000"
            - name: CART_SERVICE_ADDR
              value: "127.0.0.1:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "127.0.0.1:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "127.0.0.1:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "127.0.0.1:5050"
            - name: AD_SERVICE_ADDR
              value: "127.0.0.1:9555"
            - name: ENV_PLATFORM
              value: "gcp"